# Generated by Django 6.0.3 on 2026-03-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_all', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_destinations',
            new_name='View_All_destinations',
        ),
    ]
