# Generated by Django 6.0.3 on 2026-03-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List_destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=128)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('num_of_guests', models.IntegerField()),
                ('dollars_per_night', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage_response.list_destinations')),
            ],
        ),
    ]
