# Generated by Django 6.0.3 on 2026-03-27 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=128)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('num_of_guests', models.IntegerField()),
                ('dollars_per_night', models.IntegerField()),
                ('activities', models.CharField()),
                ('amenities', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_Pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination_pages.destination_pages')),
            ],
        ),
    ]
