# Generated by Django 6.0.3 on 2026-03-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_pages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
